name: Daily C++ GitHub Contributions

permissions:
  contents: write
on:
  schedule:
    # 11:30 AM IST (06:00 UTC)
    - cron: '0 6 * * *'
    # 07:20 PM IST (13:50 UTC)
    - cron: '50 13 * * *'

  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: pip install requests

    - name: Generate C++ Notes
      env: 
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python3 notes_generator.py

    - name: Commit and Push
      run: |
        messages=(
          "DSA note updated"
          "Learned a new DSA concept"
          "C++ DSA practice update"
          "Daily DSA learning log"
          "Studied a new algorithm"
        )
        git config user.name "Akshat Verma"
        git config user.email "Akshatverma79@users.noreply.github.com"
        git add .
        git commit -m "${messages[$RANDOM % ${#messages[@]}]}" || echo "No changes"
        git pull --rebase origin main
        git push