name: Daily C++ GitHub Contributions
permissions:
  contents: write
on:
  schedule:
    - cron: '30 1 * * *'
    - cron: '30 7 * * *'
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate C++ Notes
      run: python3 notes_generator.py

    - name: Commit and Push
      run: |
        git config user.name "Akshat Verma"
        git config user.email "Akshatverma79@users.noreply.github.com"
        git add .
        git commit -m "Daily C++ learning update" || echo "No changes"
        git pull --rebase origin main
        git push